language: objective-c
osx_image: xcode7
before_install:
    - brew update
    - brew upgrade xctool
notifications:
  email:
    - dudl@qq.com
# after_success:
#     - bash <(curl -s https://codecov.io/bash)

podfile: Example/Podfile
script:
  xctool
  -workspace Example/MLLayoutDemo.xcworkspace
  -scheme MLLayoutDemo
  -sdk iphonesimulator
  build 
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO